name: Graph Unit Test

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Preuzimanje koda (Checkout)
        uses: actions/checkout@v4

      - name: Instalacija Google Test biblioteke
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev

      - name: Kompajliranje testova
        run: g++ -std=c++23 GTest.cpp -lgtest -lgtest_main -pthread -o GTest

      - name: Pokretanje testova
        run: ./GTest